
services:
#  app:
#     image: my-store-programming
  #    build:
  #    context: .
   #ports:
    #- "8080:8080"
  #  volumes:
  #    - ./files/pg_data:/var/lib/postgresql/data
  #  environment:
  #    - spring.datasource.url=jdbc:postgresql://postgres:5432/store
  #    - spring.datasource.username=postgres
  #    - spring.datasource.password=password
  #  depends_on:
  #    - postgres


  postgres:
    image: postgres:15-bookworm
    restart: "no"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "6432:5432"
    volumes:
      - ./files/pg_data:/var/lib/postgresql/data


